name: Compile and test against PR

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "SCRIPTS_PATH=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_NAME_ENV=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/${{ env.PLUGIN_NAME_ENV }}.sp
      
      - name: Download SourcePawn plugin dependencies
        uses: Zabaniya001/SPDependy@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Parse toml
        uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'sp.toml'
          field: 'Compile.plugins'

      - name: Compile plugins
        run: |
          mkdir plugins
          my_array=$(echo ${{ toJSON(steps.read_toml.outputs.value) }} | jq -r '.[]')
          for plugin in $my_array; do
            spcomp -w234 -O2 -v2 -i"scripting/include" -i".temp/include" -o"plugins/${plugin}.smx" "scripting/${plugin}.sp"
          done
        working-directory: ${{ env.SCRIPTS_PATH }}